name: Docker Image CI

on:
  pull_request:
    branches: [main]
  push:
    branches: '*'


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install --yes jq
    - name: Build a local container image
      run: |
        ./containerize.sh 
    - name: Use image to show tag
      run: |
        t=$(./containerize.sh -q)
        docker run --rm --init -v $PWD:$PWD --workdir=$PWD $t -q
    - name: Use image to scan itself
      run: |
        t=$(./containerize.sh -q)
        docker run --rm --init -v $PWD:$PWD --workdir=$PWD -v /var/run/docker.sock:/var/run/docker.sock $t -s
